int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int sqrt_finder(int n, int root);
int _sqrt_recursion(int n);
int prime_helper(int n, int divisor);
int is_prime_number(int n);
int find_length(char *s);
int find_palindrome(char *s, int length, int index);
int is_palindrome(char *s);
